<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Session extends Model
{
    protected $fillable = [
        'CONWIPparameters_0',
        'CONWIPparameters_1',
        'KANBANparameters_0',
        'KANBANparameters_1',
        'KANBANparameters_2',
        'KANBANparameters_3',
        'KANBANparameters_4',
        'KANBANparameters_5',
        'KANBANparameters_6',
        'KANBANparameters_7',
        'KANBANparameters_8',
        'KANBANparameters_9',
        'KANBANparameters_10',
        'KANBANparameters_11',
        'KANBANparameters_12',
        'KANBANparameters_13',
        'KANBANparameters_14',
        'KANBANparameters_15',
        'MRPparameters_0',
        'MRPparameters_1',
        'MRPparameters_10',
        'MRPparameters_11',
        'MRPparameters_12',
        'MRPparameters_13',
        'MRPparameters_14',
        'MRPparameters_15',
        'MRPparameters_16',
        'MRPparameters_17',
        'MRPparameters_18',
        'MRPparameters_19',
        'MRPparameters_2',
        'MRPparameters_20',
        'MRPparameters_21',
        'MRPparameters_22',
        'MRPparameters_23',
        'MRPparameters_3',
        'MRPparameters_4',
        'MRPparameters_5',
        'MRPparameters_6',
        'MRPparameters_7',
        'MRPparameters_8',
        'MRPparameters_9',
        'averageFgi',
        'averageInv',
        'averageWip',
        'average_utilisation',
        'leadtime',
        'planningAlgoritm',
        'serviceLevel',
        'sessionName',
        'timePerPiece',
        'timePerPiece_M1',
        'timePerPiece_M2',
        'timePerPiece_M3',
        'timePerPiece_M4',
        'timePerPiece_M5',
        'total_time',
        'utilisation_M1',
        'utilisation_M2',
        'utilisation_M3',
        'utilisation_M4',
        'utilisation_M5'
    ];
}
